# The site title and description; used in feeds by default.
title = "Thinking, Slow"
sub_title = "Thoughts on the intersection of technology and society"

# The URL the site will be built for
base_url = "https://thinking-slow.eth.limo/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
theme = "punk-minima"

taxonomies = [{ name = "tags" }]

default_language = "en"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
# highlight_theme = "OneHalfLight"

[extra]
# Put all your custom variables here
# control dark mode: auto | dark | toggle
mode = "toggle"

# if set true, will use external CDN resource to load font and js file
useCDN = true

favicon = "/icon/favicon.ico"

# show in the footer
copyright = "Prudhvi Rampey"

# config your Google Analysis ID
ga = "XXXX-XXXXX"

# optional: config your i18n entry
[extra.translations]

# config multi-language menu and other text
[[extra.translations.en]]
show_more = "Read more ⟶"
previous_page = "← Previous"
next_page = "Next →"
posted_on = "on "
posted_by = ""
read_time = "minute read"
all_tags = "All tags"
menus = [
    { name = "About Me", url = "/about", weight = 1 },
    { name = "Tags", url = "/tags", weight = 2 },
    { name = "Tools", url = "/tools", weight = 3 },
]

# config social icon info in the footer
[[extra.social]]
icon = "github"
name = "GitHub"
url = "https://github.com/XXXMrG/archie-zola"

[[extra.social]]
icon = "twitter"
name = "Twitter"
url = "https://github.com/your-name/"
